# Generated by Django 4.2.2 on 2023-09-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_headlines_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
