# Generated by Django 4.2.6 on 2023-11-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0005_alter_headlines_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlines',
            name='id',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='link',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
